In [1]:
import numpy as np
import tensorflow as tf

2022-06-23 22:38:38.286206: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2022-06-23 22:38:38.378666: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-23 22:38:38.378697: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.


## Load the data

In [2]:
mnist = tf.keras.datasets.mnist

(X_train, y_train), (X_test, y_test) = mnist.load_data()

## Data Attributes

In [3]:
X_train.shape, y_train.shape

((60000, 28, 28), (60000,))

In [4]:
X_test.shape, y_test.shape

((10000, 28, 28), (10000,))

In [5]:
np.unique(y_train)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=uint8)

In [6]:
X_train.dtype, y_train.dtype

(dtype('uint8'), dtype('uint8'))

## Data type conversion

In [7]:
X_train = tf.cast(X_train, tf.float32)

X_test = tf.cast(X_test, tf.float32)

2022-06-23 22:38:50.164961: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2022-06-23 22:38:50.164999: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2022-06-23 22:38:50.165023: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (SOUPARNIKA): /proc/driver/nvidia/version does not exist
2022-06-23 22:38:50.166569: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [8]:
X_train.dtype, y_train.dtype

(tf.float32, dtype('uint8'))

## Data normalization

In [9]:
X_train = X_train / 255

X_test = X_test / 255

## One hot encoding of target variable

In [10]:
y_train = tf.keras.utils.to_categorical(y_train)

In [11]:
y_test = tf.keras.utils.to_categorical(y_test)

In [12]:
y_train.shape

(60000, 10)

In [13]:
y_train[0]

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.], dtype=float32)

## Build the model

In [52]:
def build_ann():
    '''
    Simple Artificial Neural Network
    '''
    ann_model = tf.keras.models.Sequential()
    
    ann_model.add(tf.keras.layers.Input(shape=(28, 28))) # Input Layer
    
    ann_model.add(tf.keras.layers.Flatten())
    
    ann_model.add(tf.keras.layers.Dense(10, activation='softmax')) # Output Layer
    
    return ann_model

In [53]:
def build_hidden_ann():
    '''
    Artificial Neural Network with hidden layer
    '''
    ann_model = tf.keras.models.Sequential()
    
    ann_model.add(tf.keras.layers.Input(shape=(28, 28))) # Input Layer
    
    ann_model.add(tf.keras.layers.Flatten())
    
    ann_model.add(tf.keras.layers.Dense(100, activation='relu')) # Hidden Layer
    
    ann_model.add(tf.keras.layers.Dense(10, activation='softmax')) # Output Layer
    
    return ann_model

In [54]:
def build_dropout_ann():
    '''
    Artificial Neural Network with hidden and drop out layer
    '''
    ann_model = tf.keras.models.Sequential()
    
    ann_model.add(tf.keras.layers.Input(shape=(28, 28))) # Input Layer
    
    ann_model.add(tf.keras.layers.Flatten())
    
    ann_model.add(tf.keras.layers.Dense(100, activation='relu')) # Hidden Layer
    
    ann_model.add(tf.keras.layers.Dropout(0.2)) # Dropout Layer
    
    ann_model.add(tf.keras.layers.Dense(10, activation='softmax')) # Output Layer
    
    return ann_model

In [55]:
def build_dcnn():
    '''
    Deep Convolutional Neural Network
    '''
    cnn_model = tf.keras.models.Sequential()
    
    cnn_model.add(tf.keras.layers.Input(shape=(28, 28, 1))) # Input layer
    
    cnn_model.add(tf.keras.layers.Convolution2D(filters=20, kernel_size=(5, 5), activation='relu'))
    cnn_model.add(tf.keras.layers.MaxPooling2D(pool_size=(2, 2), strides=(2, 2)))
    
    cnn_model.add(tf.keras.layers.Convolution2D(filters=50, kernel_size=(5, 5), activation='relu'))
    cnn_model.add(tf.keras.layers.MaxPooling2D(pool_size=(2, 2), strides=(2, 2)))
    
    cnn_model.add(tf.keras.layers.Flatten())
    
    cnn_model.add(tf.keras.layers.Dense(100, activation='relu')) # Hidden Layer
    
    #cnn_model.add(tf.keras.layers.Dropout(0.2)) # Dropout Layer
    
    cnn_model.add(tf.keras.layers.Dense(10, activation='softmax')) # Output Layer
    
    return cnn_model

## Compile the model

In [56]:
model = build_dcnn()

model.compile(optimizer=tf.keras.optimizers.Adam(),
             loss=tf.keras.losses.CategoricalCrossentropy(),
             metrics=['accuracy'])

## Train the model

In [57]:
tb_callback = tf.keras.callbacks.TensorBoard(log_dir='./logs/mnist/cnn/adam', histogram_freq=1)

model.fit(X_train, y_train, epochs=10, callbacks=[tb_callback])

Epoch 1/10
1875/1875 [==============================] - 8s 4ms/step - loss: 0.1319 - accuracy: 0.9595
Epoch 2/10
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0437 - accuracy: 0.9866
Epoch 3/10
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0303 - accuracy: 0.9901
Epoch 4/10
1875/1875 [==============================] - 9s 5ms/step - loss: 0.0221 - accuracy: 0.9930
Epoch 5/10
1875/1875 [==============================] - 10s 5ms/step - loss: 0.0175 - accuracy: 0.9947
Epoch 6/10
1875/1875 [==============================] - 9s 5ms/step - loss: 0.0139 - accuracy: 0.9956
Epoch 7/10
1875/1875 [==============================] - 9s 5ms/step - loss: 0.0113 - accuracy: 0.9963
Epoch 8/10
1875/1875 [==============================] - 9s 5ms/step - loss: 0.0114 - accuracy: 0.9961
Epoch 9/10
1875/1875 [==============================] - 9s 5ms/step - loss: 0.0082 - accuracy: 0.9973
Epoch 10/10
1875/1875 [==============================] - 9s 5ms/step - loss: 0.00

## Save the model to disk

In [58]:
model_json = model.to_json()

with open('mnist_model.json', 'w') as json_file:
    json_file.write(model_json)
    
model.save_weights('mnist_weights.h5')

## Model Summary

In [59]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 24, 24, 20)        520       
                                                                 
 max_pooling2d (MaxPooling2D  (None, 12, 12, 20)       0         
 )                                                               
                                                                 
 conv2d_1 (Conv2D)           (None, 8, 8, 50)          25050     
                                                                 
 max_pooling2d_1 (MaxPooling  (None, 4, 4, 50)         0         
 2D)                                                             
                                                                 
 flatten_1 (Flatten)         (None, 800)               0         
                                                                 
 dense_2 (Dense)             (None, 100)              

## Test the model

In [60]:
test_loss, test_accuracy = model.evaluate(X_test, y_test)

print('Test accuracy:', test_accuracy)

313/313 [==============================] - 1s 2ms/step - loss: 0.0477 - accuracy: 0.9905
Test accuracy: 0.9904999732971191


In [61]:
y_predict = [tf.argmax(i) for i in model.predict(X_test)]

313/313 [==============================] - 1s 2ms/step


In [62]:
list(y_test[100]).index(1), y_predict[100]

(6, <tf.Tensor: shape=(), dtype=int64, numpy=6>)

## TensorBoard

In [25]:
# tensorboard --logdir log/
%load_ext tensorboard

%tensorboard --logdir logs/mnist

## Predicting with saved model and weights

In [14]:
from skimage.transform import resize
from skimage.color import rgb2gray
from imageio import imread
from tensorflow.keras.models import model_from_json
from tensorflow.keras.optimizers import SGD

model = model_from_json(open('mnist_model.json').read())

model.load_weights('mnist_weights.h5')

In [15]:
image_names = ['Seven.jpg', 'Three.jpg']

images = [resize((imread(img)), (28, 28)).astype('float32') for img in image_names]

images = np.array(images) / 255.0

images.shape

(2, 28, 28)

In [16]:
model.compile(optimizer=tf.keras.optimizers.SGD(),
             loss=tf.keras.losses.CategoricalCrossentropy(),
             metrics=['accuracy'])

In [20]:
model.evaluate(X_test, y_test)

313/313 [==============================] - 1s 3ms/step - loss: 0.0477 - accuracy: 0.9905


[0.04768525809049606, 0.9904999732971191]

In [17]:
predictions = model.predict(images)

313/313 [==============================] - 1s 3ms/step


In [68]:
print(predictions)

[[0.09178817 0.1469521  0.08390505 0.07716288 0.10936724 0.08186859
  0.07718706 0.11258928 0.13300392 0.08617574]
 [0.09215215 0.14736803 0.08457819 0.0770119  0.10900827 0.08177542
  0.07713665 0.11271694 0.1325037  0.08574872]]


In [69]:
np.argmax(predictions, axis=1)

array([1, 1])